development:
  cloud_name: azandriacloud
  api_key: <%= ENV['AZANDRIA_BLAUGH_CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['AZANDRIA_BLAUGH_CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: azandriacloud
  api_key: <%= ENV['AZANDRIA_BLAUGH_CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['AZANDRIA_BLAUGH_CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: azandriacloud
  api_key: <%= ENV['AZANDRIA_BLAUGH_CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['AZANDRIA_BLAUGH_CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
